# Generated by Django 4.2.29 on 2026-03-21 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_systemprompt_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('aliyun', 'aliyun'), ('deepseek', 'deepseek'), ('openai', 'openai'), ('custom', 'custom')], default='aliyun', max_length=32)),
                ('api_key', models.CharField(blank=True, default='', max_length=512)),
                ('api_base', models.CharField(blank=True, default='', max_length=512)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AI Settings',
                'verbose_name_plural': 'User AI Settings',
            },
        ),
    ]
