# Generated by Django 4.2.29 on 2026-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_useraisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraisettings',
            name='provider',
            field=models.CharField(choices=[('aliyun', 'aliyun'), ('deepseek', 'deepseek'), ('minimax', 'minimax'), ('openai', 'openai'), ('custom', 'custom')], default='aliyun', max_length=32),
        ),
    ]
