# Generated by Django 4.2.29 on 2026-03-21 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_system_voices(apps, schema_editor):
    Voice = apps.get_model('web', 'Voice')
    default_voices = [
        {
            'name': '龙安洋',
            'voice_code': 'longanyang',
            'model_name': 'cosyvoice-v3-flash',
            'description': '明亮自然的青年男声，适合聊天和陪伴场景。',
            'language': 'zh-CN,en',
        },
        {
            'name': '龙橙',
            'voice_code': 'longcheng_v3',
            'model_name': 'cosyvoice-v3-flash',
            'description': '沉稳清晰的青年男声，适合讲解和问答场景。',
            'language': 'zh-CN,en',
        },
        {
            'name': '龙婉',
            'voice_code': 'longwan_v3',
            'model_name': 'cosyvoice-v3-flash',
            'description': '柔和自然的青年女声，适合陪伴和聊天场景。',
            'language': 'zh-CN,en',
        },
        {
            'name': '龙小淳',
            'voice_code': 'longxiaochun_v2',
            'model_name': 'cosyvoice-v2',
            'description': '温和亲切的中性音色，适合稳定播报。',
            'language': 'zh-CN,en',
        },
    ]

    for item in default_voices:
        Voice.objects.update_or_create(
            voice_code=item['voice_code'],
            defaults={
                'name': item['name'],
                'provider': 'aliyun',
                'source': 'system',
                'model_name': item['model_name'],
                'description': item['description'],
                'language': item['language'],
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0007_useraisettings_asr_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('provider', models.CharField(choices=[('aliyun', 'aliyun')], default='aliyun', max_length=32)),
                ('source', models.CharField(choices=[('system', 'system'), ('custom', 'custom')], default='system', max_length=16)),
                ('model_name', models.CharField(default='cosyvoice-v3-flash', max_length=128)),
                ('voice_code', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='zh-CN', max_length=64)),
                ('sample_audio', models.FileField(blank=True, null=True, upload_to='voice/samples/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='web.voice'),
        ),
        migrations.RunPython(seed_system_voices, migrations.RunPython.noop),
    ]
