# Generated by Django 4.2.29 on 2026-03-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_voice_character_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='initiative_level',
            field=models.CharField(choices=[('passive', 'passive'), ('balanced', 'balanced'), ('proactive', 'proactive')], default='balanced', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='memory_mode',
            field=models.CharField(choices=[('off', 'off'), ('standard', 'standard'), ('enhanced', 'enhanced')], default='standard', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='persona_boundary',
            field=models.CharField(choices=[('grounded', 'grounded'), ('companion', 'companion'), ('dramatic', 'dramatic')], default='companion', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='reply_length',
            field=models.CharField(choices=[('short', 'short'), ('balanced', 'balanced'), ('detailed', 'detailed')], default='balanced', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='reply_style',
            field=models.CharField(choices=[('natural', 'natural'), ('warm', 'warm'), ('restrained', 'restrained'), ('playful', 'playful')], default='natural', max_length=32),
        ),
        migrations.AddField(
            model_name='character',
            name='tools_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='tools_read_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='tools_require_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='conversation_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='friend',
            name='memory_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='relationship_memory',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_preference_memory',
            field=models.TextField(blank=True, default=''),
        ),
    ]
