# Generated by Django 4.2.29 on 2026-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_character_initiative_level_character_memory_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraisettings',
            name='chat_supports_dashscope_audio',
            field=models.BooleanField(default=False),
        ),
    ]
