# Generated by Django 4.2.29 on 2026-03-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_useraisettings_chat_supports_dashscope_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='custom_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
