# Generated by Django 4.2.29 on 2026-03-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_character_custom_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last_debug_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='last_debug_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='friend',
            name='memory_refresh_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
