# Generated by Django 4.2.29 on 2026-03-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_character_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WerewolfGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('active', 'active'), ('finished', 'finished')], default='waiting', max_length=16)),
                ('phase', models.CharField(choices=[('setup', 'setup'), ('night', 'night'), ('day_speeches', 'day_speeches'), ('vote', 'vote'), ('finished', 'finished')], default='setup', max_length=24)),
                ('day_number', models.PositiveIntegerField(default=0)),
                ('night_number', models.PositiveIntegerField(default=0)),
                ('winner', models.CharField(blank=True, choices=[('', ''), ('villagers', 'villagers'), ('wolves', 'wolves')], default='', max_length=16)),
                ('observer_note', models.TextField(blank=True, default='')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WerewolfSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('character', 'character'), ('custom', 'custom')], default='character', max_length=16)),
                ('seat_order', models.PositiveIntegerField(default=0)),
                ('display_name', models.CharField(max_length=64)),
                ('profile', models.TextField(blank=True, default='')),
                ('custom_prompt', models.TextField(blank=True, default='')),
                ('photo', models.FileField(blank=True, null=True, upload_to='werewolf/seats/photos/')),
                ('background_image', models.FileField(blank=True, null=True, upload_to='werewolf/seats/backgrounds/')),
                ('reply_style', models.CharField(choices=[('natural', 'natural'), ('warm', 'warm'), ('restrained', 'restrained'), ('playful', 'playful')], default='natural', max_length=32)),
                ('reply_length', models.CharField(choices=[('short', 'short'), ('balanced', 'balanced'), ('detailed', 'detailed')], default='balanced', max_length=32)),
                ('initiative_level', models.CharField(choices=[('passive', 'passive'), ('balanced', 'balanced'), ('proactive', 'proactive')], default='balanced', max_length=32)),
                ('memory_mode', models.CharField(choices=[('off', 'off'), ('standard', 'standard'), ('enhanced', 'enhanced')], default='off', max_length=32)),
                ('persona_boundary', models.CharField(choices=[('grounded', 'grounded'), ('companion', 'companion'), ('dramatic', 'dramatic')], default='grounded', max_length=32)),
                ('identity', models.CharField(blank=True, choices=[('wolf', 'wolf'), ('seer', 'seer'), ('villager', 'villager')], default='', max_length=16)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_revealed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['seat_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='WerewolfSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=24)),
                ('day_number', models.PositiveIntegerField(default=0)),
                ('night_number', models.PositiveIntegerField(default=0)),
                ('audience', models.CharField(choices=[('public', 'public'), ('wolves', 'wolves'), ('private', 'private')], default='public', max_length=16)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='web.werewolfgame')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='web.werewolfseat')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='werewolfseat',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werewolf_seats', to='web.character'),
        ),
        migrations.AddField(
            model_name='werewolfseat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='web.werewolfgame'),
        ),
        migrations.AddField(
            model_name='werewolfseat',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werewolf_seats', to='web.voice'),
        ),
        migrations.CreateModel(
            name='WerewolfEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('game_created', 'game_created'), ('note', 'note'), ('night_result', 'night_result'), ('day_started', 'day_started'), ('day_speeches_completed', 'day_speeches_completed'), ('vote_result', 'vote_result'), ('game_finished', 'game_finished'), ('game_reset', 'game_reset')], max_length=32)),
                ('phase', models.CharField(blank=True, default='', max_length=24)),
                ('day_number', models.PositiveIntegerField(default=0)),
                ('night_number', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.werewolfgame')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='werewolfseat',
            constraint=models.UniqueConstraint(fields=('game', 'seat_order'), name='unique_werewolf_seat_order'),
        ),
    ]
